@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":TagCommandParser" as TagCommandParser LOGIC_COLOR
participant "t:TagCommand" as TagCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
participant ":Person" as Person MODEL_COLOR
participant ":Project" as Project MODEL_COLOR
end box

[-> LogicManager : execute("tag p/91234567 proj/project-x")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("tag p/91234567 proj/project-x")
activate AddressBookParser

create TagCommandParser
AddressBookParser -> TagCommandParser
activate TagCommandParser

TagCommandParser --> AddressBookParser
deactivate TagCommandParser

AddressBookParser -> TagCommandParser : parse(" p/91234567 proj/project-x")
activate TagCommandParser

create TagCommand
TagCommandParser -> TagCommand
activate TagCommand

TagCommand --> TagCommandParser :
deactivate TagCommand

TagCommandParser --> AddressBookParser : t
deactivate TagCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
TagCommandParser -[hidden]-> AddressBookParser
destroy TagCommandParser

AddressBookParser --> LogicManager : t
deactivate AddressBookParser

LogicManager -> TagCommand : execute(m)
activate TagCommand

TagCommand -> Model : getFilteredPersonList()
activate Model

Model --> TagCommand
deactivate Model

create Project
TagCommand -> Project : new Project("project-x")
activate Project

Project --> TagCommand
deactivate Project

TagCommand -> Person : tagPerson(tags, projects)
activate Person

Person --> TagCommand : taggedPerson
deactivate Person

TagCommand -> Model : setPerson(personToTag, taggedPerson)
activate Model

Model --> TagCommand
deactivate Model

create CommandResult
TagCommand -> CommandResult
activate CommandResult

CommandResult --> TagCommand
deactivate CommandResult

TagCommand --> LogicManager : r
deactivate TagCommand

[<--LogicManager
deactivate LogicManager
@enduml
